spring.application.name=expense-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/expense_tracker
spring.datasource.username=expense_app
spring.datasource.password=Feb200725

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
